### ISSUE TITLE
selenium driver code deprecated (with updated code)

### ISSUE THREAD

**Issue by teohsinyee** [oxylabs/Scraping-Dynamic-JavaScript-Ajax-Websites-With-BeautifulSoup#1]
This is an extremely good step-by-step guideline. Kudos to the team for preparing it!

[⚠️](https://emojipedia.org/warning/)Error 1: 
```
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
```

[❌](https://emojiguide.com/symbols/cross-mark/#:~:text=The%20cross%20mark%20emoji%20shows,used%20in%20the%20same%20conversation.)We will get this error after executing the code below.
```
driver = Chrome(executable_path='c:/driver/chromedriver.exe')
```
[✔️](https://emojiguide.com/symbols/check-mark/#:~:text=check%20mark%20%E2%9C%94%EF%B8%8F&text=This%20emoji%20shows%20a%20thick,used%20to%20indicate%20completed%20tasks.)To fix this, we need to **change to this** ->
```
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=options)
```

[⚠️](https://emojipedia.org/warning/)Error 2:
```
Deprecationwarning: find_element_by_* commands are deprecated. please use find_element() instead
```
[❌](https://emojiguide.com/symbols/cross-mark/#:~:text=The%20cross%20mark%20emoji%20shows,used%20in%20the%20same%20conversation.)Deprecated code:
```
element = driver.find_element_by_class_name("author")
element = driver.find_element_by_tag_name("small")
```
[✔️](https://emojiguide.com/symbols/check-mark/#:~:text=check%20mark%20%E2%9C%94%EF%B8%8F&text=This%20emoji%20shows%20a%20thick,used%20to%20indicate%20completed%20tasks.)To fix this, we need to **change to this** ->
```
element = driver.find_element(By.CLASS_NAME, "author")
element = driver.find_element(By.TAG_NAME, "small")
```
Documentation: https://selenium-python.readthedocs.io/locating-elements.html
Thanks.

**Comment by GabijaFatenaite** [comment]
Hey,

Thanks for the kudos! Will pass it on to the team :) And thanks for the code fix propositions, fixed it per your suggestions.
